I see you sick and curled up
Like cats do
When psychos abuse them
Yeah

You want to purr
But you’re far too gone
I check your collar
And you got no name

And I know you want it
And I know you like it
And I know you got it
And I know you love

D-R-U-G-S
D-R-U-G-S
D-R-U-G-S
D-R-U-G-S

You’re full of silence
When I tell you
That cats are meant
To be cool and cute

You’re off your head
You look like a corpse
Milk-white face
Like the saddest moon

And I know you want it
And I know you like it
And I know you got it
And I know you love

D-R-U-G-S
D-R-U-G-S
D-R-U-G-S
D-R-U-G-S

And I know you want it
And I know you like it
And I know you got it
And I know you love

D-R-U-G-S
D-R-U-G-S
D-R-U-G-S
D-R-U-G-S

D-R-U-G-S
D-R-U-G-S
D-R-U-G-S
D-R-U-G-S


____________________
Name      D.R.U.G.S.
Artist    The Raveonettes
Album     In and Out of Control
Track no  8
Year      2009
